binance:
  api:
    key: YOUR_BINANCE_API_KEY
    secret: YOUR_BINANCE_API_SECRET

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web3
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.webfluxweb3.entity
